/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchImport } from './routes/search'

// Create Virtual Routes

const StreamLazyImport = createFileRoute('/stream')()
const SignInLazyImport = createFileRoute('/sign-in')()
const PartyLazyImport = createFileRoute('/party')()
const GetPremiumLazyImport = createFileRoute('/get-premium')()
const CreateAnAccountLazyImport = createFileRoute('/create-an-account')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const StreamLazyRoute = StreamLazyImport.update({
  path: '/stream',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/stream.lazy').then((d) => d.Route))

const SignInLazyRoute = SignInLazyImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in.lazy').then((d) => d.Route))

const PartyLazyRoute = PartyLazyImport.update({
  path: '/party',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/party.lazy').then((d) => d.Route))

const GetPremiumLazyRoute = GetPremiumLazyImport.update({
  path: '/get-premium',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/get-premium.lazy').then((d) => d.Route))

const CreateAnAccountLazyRoute = CreateAnAccountLazyImport.update({
  path: '/create-an-account',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/create-an-account.lazy').then((d) => d.Route),
)

const SearchRoute = SearchImport.update({
  path: '/search',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/search.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchImport
      parentRoute: typeof rootRoute
    }
    '/create-an-account': {
      id: '/create-an-account'
      path: '/create-an-account'
      fullPath: '/create-an-account'
      preLoaderRoute: typeof CreateAnAccountLazyImport
      parentRoute: typeof rootRoute
    }
    '/get-premium': {
      id: '/get-premium'
      path: '/get-premium'
      fullPath: '/get-premium'
      preLoaderRoute: typeof GetPremiumLazyImport
      parentRoute: typeof rootRoute
    }
    '/party': {
      id: '/party'
      path: '/party'
      fullPath: '/party'
      preLoaderRoute: typeof PartyLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  SearchRoute,
  CreateAnAccountLazyRoute,
  GetPremiumLazyRoute,
  PartyLazyRoute,
  SignInLazyRoute,
  StreamLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/search",
        "/create-an-account",
        "/get-premium",
        "/party",
        "/sign-in",
        "/stream"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/search": {
      "filePath": "search.tsx"
    },
    "/create-an-account": {
      "filePath": "create-an-account.lazy.tsx"
    },
    "/get-premium": {
      "filePath": "get-premium.lazy.tsx"
    },
    "/party": {
      "filePath": "party.lazy.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.lazy.tsx"
    },
    "/stream": {
      "filePath": "stream.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
